name: lc_design
description: LC Design.
version: 1.0.0
homepage: https://github.com/stevennguyenn/lc_design

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: 3.0.1
  #datetime
  intl: 0.17.0
  #timepicker
  flutter_datetime_picker: 1.5.1
  #bottomsheet
  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  #email
  email_validator: 2.1.17
  #check phone number
  phone_number: 1.0.0
  #language
  easy_localization: 3.0.1
  #network image
  cached_network_image: 3.2.3
  #pull refresh
  pull_to_refresh: 2.0.0
  #loading styled
  loading_indicator: 3.1.0
  #switch widget
  flutter_switch: 0.3.2
  #local storage
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_secure_storage: 7.0.1
  #pincode
  pin_code_fields: 7.4.0
  #dashed border
  dotted_border: 2.0.0+3
  #push notification
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
  flutter_local_notifications: 13.0.0
  flutter_app_badger: 1.5.0
  path_provider: 2.0.11
  http: 0.13.5
  photo_view: 0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
